services:
  telegram_bot:
    build:
      context: .
      dockerfile: DockerFile
    container_name: medical_telegram_bot
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./logs:/app/logs
      - ./lightrag_data_docker:/app/lightrag_storage
